MVC_SoporteCF/Models/Aviso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcSoporteCF.Models
{
    public class Aviso
    {
        public int Id { get; set; }
        [Display(Name = "Descripción del problema")]
        [Required(ErrorMessage = "La descripción del aviso es un campo requerido.")]
        public string Descripcion { get; set; }
        [Display(Name = "Fecha de aviso")]
        [Required(ErrorMessage = "La fecha en que se realiza el aviso es un campo requerido.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaAviso { get; set; }
        [Display(Name = "Fecha de cierre")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCierre { get; set; }
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; }
        [Display(Name = "Empleado")]
        public int EmpleadoId { get; set; }
        [Display(Name = "Ipo de avería")]
        public int TipoAveriaId { get; set; }
        [Display(Name = "Equipo")]
        public int EquipoId { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual TipoAveria TipoAveria { get; set; }
        public virtual Equipo Equipo { get; set; }
    }
}

MVC_SoporteCF/Controllers/AvisosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSoporteCF.Models;
using PagedList;

namespace MvcSoporteCF.Controllers
{
    public class AvisosController : Controller
    {
        private SoporteContexto db = new SoporteContexto();

        // GET: Avisos
        public ActionResult Index(string strTipoAveria, string strCadenaBusqueda, int? page,
string strBusquedaActual, string strFiltroActual)
        {
            // Para mostrar la primera página cuando se ha introducido una cadena de búsqueda
            if (strCadenaBusqueda != null)
            {
                page = 1;
            }
            else
            {
                strCadenaBusqueda = strBusquedaActual;
            }
            ViewBag.BusquedaActual = strCadenaBusqueda;
            // Para mostrar la primera página cuando se ha cambiado la selección en el DropDownList
            if (strTipoAveria != null)
            {
                page = 1;
            }
            else
            {
                strTipoAveria = strFiltroActual;
            }
            ViewBag.FiltroActual = strTipoAveria;

            var avisos = db.Avisos.Include(a => a.Empleado).Include(a => a.Equipo).Include(a => a.TipoAveria);
            
            // Para ordenar por FechaAviso
            avisos = avisos.OrderByDescending(s => s.FechaAviso); 
            
            // Para presentar los tipos de avería en la vista
            var lstTipoAveria = new List<string>();
            var qryTipoAveria = from d in db.TipoAverias
                                orderby d.Descripcion
                                select d.Descripcion;
            lstTipoAveria.Add("Todas");
            lstTipoAveria.AddRange(qryTipoAveria.Distinct());
            ViewBag.ListaTipoAverias = new SelectList(lstTipoAveria);
           
            // Para buscar avisos por nombre de empleado en la lista de valores
            if (!String.IsNullOrEmpty(strCadenaBusqueda))
            {
                avisos = avisos.Where(s => s.Empleado.Nombre.Contains(strCadenaBusqueda));
            }

            // Para presentar los avisos filtrados por tipo de avería
            if (!string.IsNullOrEmpty(strTipoAveria))
            {
                if (strTipoAveria != "Todas")
                {
                    avisos = avisos.Where(x => x.TipoAveria.Descripcion == strTipoAveria);

                }
            }

            // Características de la paginación
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(avisos.ToPagedList(pageNumber, pageSize));
            //return View(avisos.ToList());
        }

        // GET: Avisos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = db.Avisos.Find(id);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            return View(aviso);
        }

        // GET: Avisos/Create
        public ActionResult Create()
        {
            ViewBag.EmpleadoId = new SelectList(db.Empleados, "Id", "Nombre");
            ViewBag.EquipoId = new SelectList(db.Equipos, "Id", "CodigoEquipo");
            ViewBag.TipoAveriaId = new SelectList(db.TipoAverias, "Id", "Descripcion");
            return View();
        }

        // POST: Avisos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descripcion,FechaAviso,FechaCierre,Observaciones,EmpleadoId,TipoAveriaId,EquipoId")] Aviso aviso)
        {
            if (ModelState.IsValid)
            {
                db.Avisos.Add(aviso);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpleadoId = new SelectList(db.Empleados, "Id", "Nombre", aviso.EmpleadoId);
            ViewBag.EquipoId = new SelectList(db.Equipos, "Id", "CodigoEquipo", aviso.EquipoId);
            ViewBag.TipoAveriaId = new SelectList(db.TipoAverias, "Id", "Descripcion", aviso.TipoAveriaId);
            return View(aviso);
        }

        // GET: Avisos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = db.Avisos.Find(id);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleados, "Id", "Nombre", aviso.EmpleadoId);
            ViewBag.EquipoId = new SelectList(db.Equipos, "Id", "CodigoEquipo", aviso.EquipoId);
            ViewBag.TipoAveriaId = new SelectList(db.TipoAverias, "Id", "Descripcion", aviso.TipoAveriaId);
            return View(aviso);
        }

        // POST: Avisos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion,FechaAviso,FechaCierre,Observaciones,EmpleadoId,TipoAveriaId,EquipoId")] Aviso aviso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aviso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleados, "Id", "Nombre", aviso.EmpleadoId);
            ViewBag.EquipoId = new SelectList(db.Equipos, "Id", "CodigoEquipo", aviso.EquipoId);
            ViewBag.TipoAveriaId = new SelectList(db.TipoAverias, "Id", "Descripcion", aviso.TipoAveriaId);
            return View(aviso);
        }

        // GET: Avisos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = db.Avisos.Find(id);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            return View(aviso);
        }

        // POST: Avisos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Aviso aviso = db.Avisos.Find(id);
            db.Avisos.Remove(aviso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_SoporteCF/Views/Avisos/Create.cshtml
@model MvcSoporteCF.Models.Aviso

@{
    ViewBag.Title = "Create";
}

<h2>Crear Aviso</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Aviso</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAviso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.FechaAviso).ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)
                @Html.ValidationMessageFor(model => model.FechaAviso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCierre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.FechaCierre).ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)
                @Html.ValidationMessageFor(model => model.FechaCierre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpleadoId, "EmpleadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpleadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoAveriaId, "TipoAveriaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoAveriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoAveriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EquipoId, "EquipoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EquipoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EquipoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_SoporteCF/Views/Avisos/Delete.cshtml
@model MvcSoporteCF.Models.Aviso

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar Avisos</h2>

<h3>¿Estas seguro de que quieres borrar?</h3>
<div>
    <h4>Aviso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empleado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Equipo.CodigoEquipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipo.CodigoEquipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAveria.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAveria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAviso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAviso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCierre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCierre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observaciones)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

MVC_SoporteCF/Views/Avisos/Details.cshtml
@model MvcSoporteCF.Models.Aviso

@{
    ViewBag.Title = "Details";
}

<h2>Detailles</h2>

<div>
    <h4>Aviso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empleado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Equipo.CodigoEquipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipo.CodigoEquipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAveria.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAveria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAviso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAviso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCierre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCierre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observaciones)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la lista", "Index")
</p>

MVC_SoporteCF/Views/Avisos/Edit.cshtml
@model MvcSoporteCF.Models.Aviso

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Avisos</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Aviso</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAviso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.FechaAviso).ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)
                @Html.ValidationMessageFor(model => model.FechaAviso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCierre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.FechaCierre).ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)
                @Html.ValidationMessageFor(model => model.FechaCierre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpleadoId, "EmpleadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpleadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoAveriaId, "TipoAveriaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoAveriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoAveriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EquipoId, "EquipoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EquipoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EquipoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_SoporteCF/Views/Avisos/Index.cshtml
@* @model IEnumerable<MvcSoporteCF.Models.Aviso> *@
@model PagedList.IPagedList<MvcSoporteCF.Models.Aviso>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>Avisos</h2>

<p>
    @Html.ActionLink("Nuevo", "Create")
	@* Para buscar por nombre de empleado en la lista de valores *@
	@using (Html.BeginForm("Index","Avisos",FormMethod.Get))
	{
		<p>
			Tipo de Avería: @Html.DropDownList("strTipoAveria",
							(IEnumerable<SelectListItem>)ViewBag.ListaTipoAverias,
							ViewBag.FiltroActual as string)
			Nombre del empleado: @Html.TextBox("strCadenaBusqueda", ViewBag.BusquedaActual as string)
			<input type="submit" value="Buscar" />
		</p>
	}
</p>
<table class="table">
    <tr>
		<th>
			@* @Html.DisplayNameFor(model => model.Empleado.Nombre) *@
			Nombre del empleado
		</th>
		<th>
			@* @Html.DisplayNameFor(model => model.Equipo.CodigoEquipo) *@
			Equipo
		</th>
		<th>
			@* @Html.DisplayNameFor(model => model.TipoAveria.Descripcion) *@
			Tipo de avería
		</th>
		<th>
			@* @Html.DisplayNameFor(model => model.Descripcion) *@
			Descripción
		</th>
		<th>
			@* @Html.DisplayNameFor(model => model.FechaAviso) *@
			Fecha de aviso
		</th>
		<th>
			@* @Html.DisplayNameFor(model => model.FechaCierre) *@
			Fecha de cierre
		</th>
		<th>
			@* @Html.DisplayNameFor(model => model.Observaciones) *@
			Observaciones
		</th>
		<th></th>
	</tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Empleado.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Equipo.CodigoEquipo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoAveria.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaAviso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaCierre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Observaciones)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<br />
@* Se muestra el número de páginas y el total de páginas *@
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@* Se muestran los botones de paginación mediante el helper PagedListPager *@
@Html.PagedListPager(Model, page => Url.Action("Index",
	new { page, strBusquedaActual = ViewBag.BusquedaActual, strFiltroActual = ViewBag.FiltroActual }))