MVC_SoporteCF/Controllers/TipoAveriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSoporteCF.Models;

namespace MvcSoporteCF.Controllers
{
    public class TipoAveriasController : Controller
    {
        private SoporteContexto db = new SoporteContexto();

        // GET: TipoAverias
        public ActionResult Index()
        {
            return View(db.TipoAverias.ToList());
        }

        // GET: TipoAverias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoAveria tipoAveria = db.TipoAverias.Find(id);
            if (tipoAveria == null)
            {
                return HttpNotFound();
            }
            return View(tipoAveria);
        }

        // GET: TipoAverias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoAverias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descripcion")] TipoAveria tipoAveria)
        {
            if (ModelState.IsValid)
            {
                db.TipoAverias.Add(tipoAveria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoAveria);
        }

        // GET: TipoAverias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoAveria tipoAveria = db.TipoAverias.Find(id);
            if (tipoAveria == null)
            {
                return HttpNotFound();
            }
            return View(tipoAveria);
        }

        // POST: TipoAverias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion")] TipoAveria tipoAveria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoAveria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoAveria);
        }

        // GET: TipoAverias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoAveria tipoAveria = db.TipoAverias.Find(id);
            if (tipoAveria == null)
            {
                return HttpNotFound();
            }
            return View(tipoAveria);
        }

        // POST: TipoAverias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoAveria tipoAveria = db.TipoAverias.Find(id);
            db.TipoAverias.Remove(tipoAveria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_SoporteCF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Soporte Informático</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
	@* Añadido para Datapicker de JQueryUIHelpers.Mvc5 *@
	@Styles.Render("~/Content/themes/base/css")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Soporte informático", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
					<li>@Html.ActionLink("Avisos", "Index", "Avisos")</li>
					<li>@Html.ActionLink("Equipos", "Index", "Equipos")</li>
					<li>@Html.ActionLink("Localizaciones", "Index", "Localizaciones")</li>
					<li>@Html.ActionLink("Averías", "Index", "TipoAverias")</li>
					<li>@Html.ActionLink("Empleados", "Index", "Empleados")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Soporte informático</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
	@* Añadido para Datapicker de JQueryUIHelpers.Mvc5 *@
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/jqueryui")
	
    @RenderSection("scripts", required: false)
</body>
</html>